### ISSUE TITLE
add a feature so that the chest in the jungle temple cannot be opened before plantera is defeated, because people can enter the temple using a glitch,Add a feature to remove deerclops if there is no player nearby after a few minutes, because deerclops do not disappear even if the player is dead

### ISSUE THREAD

**Issue by Hexagonforce12** [Soof4/QoL#11]

**Comment by LiteralSoofa** [comment]
good idea

**Comment by sors89** [comment]
why not just despawn deerclops instantly after all players were dead? Implementing a timing for this sounds kinda redundant

**Comment by LiteralSoofa** [comment]
> why not just despawn deerclops instantly after all players were dead?

this could still lead to abusing the boss like queen bee. where some player teleports away when they're low hp till others respawn

**Comment by LiteralSoofa** [comment]
I've added both features but, i'll need to test before releasing a new version (in a few hours)

**Comment by LiteralSoofa** [comment]
Both features are added in [v1.3.0](https://github.com/Soof4/QoL/releases/tag/v1.3.0)
