### ISSUE TITLE
Qol api error message console problem

### ISSUE THREAD

**Issue by itsFrankV22** [Soof4/QoL#9]
This message appears all the time even if I updated to the latest version of the plugin

[Server API] Warning Plugin "QoL" has had an unhandled exception thrown by one of its ServerLeave handlers: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at QoL.Handlers.OnServerLeave(LeaveEventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args) in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/HandlerCollection.cs:line 109
152.207.150.203:18889 is connecting...
65.108.224.31:57784 is connecting...
[Server API] Warning Plugin "QoL" has had an unhandled exception thrown by one of its ServerLeave handlers: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at QoL.Handlers.OnServerLeave(LeaveEventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args) in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/HandlerCollection.cs:line 109
65.108.224.31:53790 is connecting...
[Server API] Warning Plugin "QoL" has had an unhandled exception thrown by one of its ServerLeave handlers: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at QoL.Handlers.OnServerLeave(LeaveEventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args) in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/HandlerCollection.cs:line 109
[SEconomy Journal] Writing to disk
[SEconomy Journal] Finished backing up.
65.108.224.31:38532 is connecting...
152.207.150.203:18890 is connecting...
[Server API] Warning Plugin "QoL" has had an unhandled exception thrown by one of its ServerLeave handlers: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at QoL.Handlers.OnServerLeave(LeaveEventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args) in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/HandlerCollection.cs:line 109

**Comment by LiteralSoofa** [comment]
I'll look into this some time today and upload a new version. Ty for reporting.

**Comment by itsFrankV22** [comment]
ok by the way thank you very much I use several of your plugins on my server and they are very good

I also put /builder and nothing happened, I still don't understand how it works And I have the permission, I got it with find perm

**Comment by LiteralSoofa** [comment]
This has been fixed, you can update to v1.2.5.

Thank you for the compliments. <3

``/builder`` should activate the journey menu. If it didn't work, could you maybe check your logs and find if there is anything related, and send them to me? Or, maybe give some information about your world, device, etc. It had a problem of crashing someone's game (Windows) before, but when i tested it on my devices (Ubuntu and Android) i had no problems.

**Comment by itsFrankV22** [comment]
Right now I'm not at home but the server is x64 tshock I don't know which operating system hosts it in the cloud but I'm from a PC and when I put /builder nothing happens it just gets stuck For 5 seconds and then everything starts Moving around and the messages load as if what happened was a crash and for a moment the server and my PC stopped sending packets, so 5sec

This is the best explanation I can give, if you need something else just guide me, I can send a video if necessary, all for contributing

A pleasure to help you

[Edit] I haven't updated to the most recent version yet, I'll let you know if everything goes well. 

After putting /builder, my character changed color to random skin and clothing colors, but the most important thing is that without the godmode I forgot to activate it by accident I died from the wand of discord and I dropped everything as if I were a medium core, this doesn't happen to other players, only me

**Comment by LiteralSoofa** [comment]
Huh.. It sounds like packet was written wrong.. I'll look around and try to find something. Thank you so much for the explanation, that was helpful.

**Comment by LiteralSoofa** [comment]
``/builder`` command's bug is now fixed in [v1.2.6](https://github.com/Soof4/QoL/releases/tag/v1.2.6)
